server:
  port: 8001
spring:
  application:
    name: person-service
  datasource:
    url: jdbc:h2:file:./schema
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema.sql