log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":6154"

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true
      
global:
  sendAnonymousUsage: true